[toolchain]
channel = "nightly-2025-12-01"
components = ["rust-src", "rustfmt", "clippy", "llvm-tools", "rust-analyzer"]
target = ["aarch64-linux-android", "armv7-linux-androideabi", "i686-linux-android", "x86_64-linux-android", "x86_64-unknown-linux-gnu"]
